# Example

```{r}
library(tidyverse)
```

## 数据准备

```{r}
set.seed(123)                 #设定随机种子，保证做的图和这里的一样#
df <- data.frame(
  var=LETTERS[1:10],    #字母A-J#
  id=1:10,                        #数字1-10#
  a=runif(10),                  #10个随机数#
  b=runif(10),                  #10个随机数#
  c=runif(10),                  #10个随机数#
  stringsAsFactors = F   #不转换为因子#
)
df1 <- gather(df,"item",value,-1:-2)
df1$item_id<-rep(1:3,each=10);df1
```

## 簇状柱形图

```{r}
ggplot(df1,aes(var,value))+
  geom_bar(aes(fill=item),stat ="identity",position="dodge",width=0.8)
```

## 堆积柱形图

```{r}
ggplot(df1,aes(var,value))+
  geom_bar(aes(fill=item),stat = "identity",position="stack",width=0.8)

```

## 百分比堆积柱形图

```{r}
ggplot(df1,aes(var,value))+
  geom_bar(aes(fill=item),stat = "identity",position="fill",width=0.8)
```

## 饼图 1

```{r}
p<-ggplot(df,aes(x="1",a,fill=var))+ geom_bar(stat="identity");
p   #width=1 同心圆可闭合#
```

```{r}
p+coord_polar(theta="y")
```

```{r}
p+coord_polar(theta="x")
```

## 饼图 2

```{r}
p<-ggplot(df1,aes(x = item,value,fill=var))+
     geom_bar(stat="identity",position="fill",width=1);p
```

```{r}
p+coord_polar(theta="y")
```

```{r}
p+coord_polar(theta="x")
```

## 饼图 3

```{r}
p<-ggplot(df,aes(x = "1",a,fill=factor(var)))+ geom_bar(stat="identity",position="dodge");p
```

```{r}
p+coord_polar(theta="y")
```

```{r}
p+coord_polar(theta="x")
```

## 普通折线图

```{r}
ggplot(df1,aes(id,value,colour=item))+
  geom_line(size=1)+
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 堆积折线图

```{r}
ggplot(df1,aes(id,value,colour=item))+
  geom_line(position="stack",size=3,linetype=6)+
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 百分比堆积折线图

```{r}
ggplot(df1,aes(id,value,colour=item))+
  geom_line(position="fill")+
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 带标记的折线图

```{r}
p<-ggplot(df1,aes(id,value,colour=item))
p+geom_line(linetype=3)+geom_point(shape=10,size=3)
```

## 带标记的堆积折线图

```{r}
ggplot(df1,aes(id,value,colour=item))+
  geom_line(position="stack",size=1)+
  geom_point(position="stack",size=5,shape=10)+
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 带标记百分比堆积折线图

```{r}
ggplot(df1,aes(id,value,colour=item))+
  geom_line(position="fill")+
  geom_point(position="fill")+
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 散点图和气泡图

```{r}
p<-ggplot(df1,aes(var,value,colour=item))
p+geom_point(aes(size=value*1.5))
```

## 面积图

```{r}
ggplot(df1,aes(id,value))+
  geom_area(aes(fill=item), position="dodge", alpha=0.5)+  #position_dodge(width=0)
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 堆积面积图

```{r}
ggplot(df1,aes(id,value))+
  geom_area(aes(fill=item), position="stack", alpha=0.5)+  #position=“stack”可省
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 百分比堆积面积图

```{r}
ggplot(df1,aes(id,value))+
  geom_area(aes(fill=item),position="fill",alpha=0.5)+
  scale_x_continuous(breaks = 1:10,labels = LETTERS[1:10])
```

## 箱线图

```{r}
ggplot(df1,aes(item,value,colour=item))+
  geom_boxplot(aes(fill=item),alpha=0.2,
               outlier.colour = "red",
               outlier.shape = 2,
               outlier.size = 5,
               coef=1.5)+
  geom_jitter(width = 0.1)
```

## 直方图

```{r}
ggplot(df1,aes(value))+
  geom_histogram(bins=10,colour="white")
```
